### ISSUE TITLE
Setting DAG every time record is saved / setData instance error

### ISSUE THREAD

**Issue by lizohsu** [vanderbilt-redcap/auto-dags-module#2]
Every time a record is saved the setDAG method is called and the DAG is assigned again.

The DAG should only be assigned once and then re-assigned if it's changed.

Because the DAG is assigned every time a record is saved, the setData method is called, but the setData method fails for repeating forms, when the instance is greater than 1. Generating lots of exception / error messages.

**Comment by mmcev106** [comment]
I'm sorry, that definitely sounds like a legitimate problem...  Unfortunately our team is not generally able to spend time supporting modules unless the work is billable.  We try to review and merge pull requests quickly though.
